### ISSUE TITLE
Notebook Talk for JupyterCon 2023

### ISSUE THREAD

**Issue by echarles** [jupyter/notebook-team-compass#22]
The proposal for the Notebook talk at JupyterCon 2023 has been selected 🙌️

We should sync to prepare that:

- [ ] JupyterCon 2023 slide template
- [ ] Place to host the slide (Google Docs...?)
- [ ] Define the speakers

The accepted proposal is `The past, present and future of the Jupyter Notebook` (proposed speakers by alphabetical order: Eric Charles, Eric Gentry, Jeremy Tuloup, Rosio Reyes)

```
Jupyter Notebook 7 is being developed as a replacement for users who may have been previously using Notebook 6 and want more of the features being created for JupyterLab, like real-time collaboration, debuggers, theming, and internationalization, among other benefits.

To ensure that those users are equipped with some essential knowledge that will help them smoothly transition to using Notebook 7, this talk will go over some of the key details of working with the new Jupyter Notebook. We will explain how users can run multiple frontends like Notebook 7, JupyterLab and NbClassic (the long term supported version of the Notebook 6 code base) that will ease the transition of users not ready to switch to Notebook 7 as well as give users the freedom to choose between the Notebook 7 and Lab interface based on project needs.

Through this talk we will also aim to provide Notebook 6 extension developers with information about the resources available to aid the transition of their extensions to both Notebook 7 and JupyterLab.  Notebook users will leave this talk having a better understanding of what next steps they may want to take to get started with Notebook 7.
```

```
This talk presumes the release of Jupyter Notebook 7 by May. Notebook 7 has currently been alpha released, 7.0.0a9, and is likely to be officially released in the near future. 

However, we can adapt the talk slightly if Jupyter Notebook 7 has not quite been released by JupyterCon.
```

@jupyter/notebook-council

**Comment by jtpio** [comment]
FYI I gave a presentation today at PyConDE & PyData Berlin 2023 about "The Future of the Jupyter Notebook interface". 

The slides are on this repo: https://github.com/jtpio/pyconde-pydata-berlin-2023-notebook-7
Live version on GitHub Pages: http://jtpio.github.io/pyconde-pydata-berlin-2023-notebook-7/

The slides are written in Markdown and built with [marp](https://marp.app/). Happy to reuse parts or most of it for JupyterCon if folks would like to. We can expand or shrink some sections.

For reference it took 25 minutes to go through all the slides with 1 speaker.

**Comment by jtpio** [comment]
Closing as the talk was done last week.

The recording will likely be available on YouTube in the coming weeks.
