### ISSUE TITLE
Start this weeks notebook call 30 minutes earlier / have it 1 hour long to discuss Notebook 7 blogpost

### ISSUE THREAD

**Issue by andrii-i** [jupyter/notebook-team-compass#26]
Last week during the notebook call we did not have enough time to discuss all items on the agenda. Taking into account that RC0 (https://github.com/jupyter/notebook/releases/tag/v7.0.0rc0) was just released, it would be great finalize the blog and have it ready for the release. 

I propose to start this weeks notebook call 30 minutes earlier / have it 1 hour long so that during the call we could do a final pass on the blog post and create a final draft on Medium from the Jupyter account so we would have everything ready. 

- Blogpost draft: https://hackmd.io/6kExBNFcRZCIpBtQDrB0ow?both
- Comment about last feedback from EC (https://github.com/jupyter/notebook-team-compass/issues/24#issuecomment-1593518927):
> Today during office hours EC reviewed Notebook 7 blogpost draft (https://hackmd.io/6kExBNFcRZCIpBtQDrB0ow?both), made edits, and added comments. They liked the overall message and tone (it was pointed out that adding a bit more of "marketing" language might be beneficial though). They also asked us to go over the blogpost again cleaning the grammar, adding links, and taking comments into account. To publish the Medium from the Jupyter account instead of a personal account, we should email the request to do so to @blink1073 and @Ruv7.
>
> From my point of view, blogpost should be published the same day / next day after Notebook 7 release so we should review it finalize by the time Notebook 7 is out.

**Comment by jtpio** [comment]
Sounds good, thanks @andrii-i for the suggestion :+1:

**Comment by andrii-i** [comment]
Closing as done
