### ISSUE TITLE
Close old issues in the notebook repo

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook-team-compass#27]
As the Notebook 7 final release is approaching (https://github.com/jupyter/notebook/issues/6307), many issues reported the past years in the notebook repo will either not be relevant anymore, or will be fixed by the new version.

I already spent some time closing a few of them today:

- https://github.com/jupyter/notebook/issues/395
- https://github.com/jupyter/notebook/issues/558
- https://github.com/jupyter/notebook/issues/594
- https://github.com/jupyter/notebook/issues/672
- https://github.com/jupyter/notebook/issues/870
- https://github.com/jupyter/notebook/issues/872
- https://github.com/jupyter/notebook/issues/921
- https://github.com/jupyter/notebook/issues/1228
- https://github.com/jupyter/notebook/issues/1246
- https://github.com/jupyter/notebook/issues/1381
- https://github.com/jupyter/notebook/issues/1754
- https://github.com/jupyter/notebook/issues/2149
- https://github.com/jupyter/notebook/issues/2219
- https://github.com/jupyter/notebook/issues/2294
- https://github.com/jupyter/notebook/issues/2594
- https://github.com/jupyter/notebook/issues/2569
- https://github.com/jupyter/notebook/issues/2712
- https://github.com/jupyter/notebook/issues/2768
- https://github.com/jupyter/notebook/issues/2809
- https://github.com/jupyter/notebook/issues/2735
- https://github.com/jupyter/notebook/issues/2758
- https://github.com/jupyter/notebook/issues/2882
- https://github.com/jupyter/notebook/issues/2765
- https://github.com/jupyter/notebook/issues/2762
- https://github.com/jupyter/notebook/issues/2795
- https://github.com/jupyter/notebook/issues/2807
- https://github.com/jupyter/notebook/issues/2894
- https://github.com/jupyter/notebook/issues/2908
- https://github.com/jupyter/notebook/issues/2891
- https://github.com/jupyter/notebook/issues/3094
- https://github.com/jupyter/notebook/issues/3103
- https://github.com/jupyter/notebook/issues/3327
- https://github.com/jupyter/notebook/issues/3416
- https://github.com/jupyter/notebook/issues/3445
- https://github.com/jupyter/notebook/issues/3609
- https://github.com/jupyter/notebook/issues/3612
- https://github.com/jupyter/notebook/issues/1626
- https://github.com/jupyter/notebook/issues/1498
- https://github.com/jupyter/notebook/issues/3198
- https://github.com/jupyter/notebook/issues/3717
- https://github.com/jupyter/notebook/issues/3178
- https://github.com/jupyter/notebook/issues/3102
- https://github.com/jupyter/notebook/issues/5712
- https://github.com/jupyter/notebook/issues/4421

It would be great to continue this effort and lower the number of issues over time.

This could be done:

- as part of the regular triage meeting
- at the end of the regular notebook weekly meeting
- during a dedicated call
- asynchronously by anyone who would like to take some time to review old issues

cc @jupyter/notebook-council for awareness

**Comment by andrii-i** [comment]
There is a huge volume of unclosed issues in the jupyter repo as well. Dedicated call might be a good idea.

**Comment by jtpio** [comment]
Did another pass at closing outdated accessibility issues that were for the classic notebook frontend: https://github.com/jupyter/notebook/issues?q=is%3Aissue+label%3Atag%3AAccessibility+is%3Aclosed

Closing this issue as a follow-up to https://github.com/jupyter/notebook-team-compass/pull/32.

But we should indeed still consider doing more rounds of closing issues, as there are still 1913 open issues as of February 21st 2024, and many of them likely don't apply to Notebook 7 anymore:

![image](https://github.com/jupyter/notebook-team-compass/assets/591645/35a9520b-0008-4b60-80d3-68f00bd1ff66)

Something to continue discussing on the Jupyter Frontends team compass, or during the Triage meeting: https://github.com/jupyterlab/team-compass

Thanks all!
