### ISSUE TITLE
Extend Wednesday July 26 notebook call to 1 hour to finalize Notebook 7 blogpost

### ISSUE THREAD

**Issue by andrii-i** [jupyter/notebook-team-compass#29]
I updated Notebook 7 Hackmd draft (https://hackmd.io/6kExBNFcRZCIpBtQDrB0ow) but there are a couple of sections I'm not sure about items left: 
- Migrating to Notebook 7 - should updates be just accepted?
- Next steps - should we delete this section? 
- Authors - not sure what would go here

Let's extend Wednesday July 26 notebook call to 1 hour so we could finalize Notebook 7 blogpost and submit it for publishing.

**Comment by andrii-i** [comment]
CC @afshin, @jtpio for awareness and visibility

**Comment by jtpio** [comment]
Sounds good thanks @andrii-i for the suggestion :+1:

**Comment by andrii-i** [comment]
@jtpio @afshin, could you please extend the tomorrow's meeting to be 1 hour / start at the top of the hour and end as usual?

**Comment by andrii-i** [comment]
(I don't have calendar write access)

**Comment by blink1073** [comment]
I've updated the meeting

**Comment by andrii-i** [comment]
Thanks @blink1073
