### ISSUE TITLE
Move the meeting notes to this repo

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook-team-compass#3]
Now that there is a Notebook Team Compass repo, we can move the meetings notes currently archived in https://github.com/jupyterlab/team-compass/issues/133 here.

Meeseeks can help us with the transfer.

**Comment by jtpio** [comment]
Migration attempted in https://github.com/jupyterlab/team-compass/issues/133#issuecomment-1022497178.

But it looks like we would need to configure this repo: https://github.com/jupyterlab/team-compass/issues/133#issuecomment-1022497199

cc @Zsailer who might be able to help with this. Thanks!

**Comment by Zsailer** [comment]
Done! 😎

**Comment by jtpio** [comment]
Thanks!

We should also update the links listed in the top comment:

![image](https://user-images.githubusercontent.com/591645/151229873-3ed6a97c-e4e4-46d3-bbfc-eb82935c0236.png)

https://github.com/jupyter/notebook-team-compass/issues/5#issue-1115380888

And maybe we could also delete some unnecessary comments such as:

- https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1022503473
- https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1022503489
- https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1022503505
