### ISSUE TITLE
Rename the `jupyter/notebook` repo default branch to `main`

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook-team-compass#6]
As part of https://github.com/jupyter/notebook/issues/6266, we should consider renaming the default branch of the https://github.com/jupyter/notebook/ repo to `main`.

Many Jupyter subprojects have already done it:

- https://github.com/jupyter-server/jupyter_server
- https://github.com/jupyterlab/lumino
- https://github.com/jupyterhub/jupyterhub/

And GitHub now defaults to `main` when creating a new repo.

This can be done automatically via the GitHub UI:

![image](https://user-images.githubusercontent.com/591645/154474438-a7ba320b-ee67-48d6-af57-150991379675.png)

**Comment by jtpio** [comment]
cc @Zsailer @kevin-bates since you have been maintaining the repo over the past months

Let me know if you have any concerns about the branch renaming. Otherwise I would suggest we do it this week.

**Comment by kevin-bates** [comment]
This sounds fine to me - thank you Jeremy!
