### ISSUE TITLE
Update issue templates for the `jupyter/notebook` repo

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook-team-compass#7]
Right now opening a new issue on the `jupyter/notebook` repo gives a very limited set of choices: https://github.com/jupyter/notebook/issues/new/choose

![image](https://user-images.githubusercontent.com/591645/154474728-fd50c562-f03c-4376-9f5c-0ed5a8192585.png)

This is because the classic notebook v6 has been in maintenance mode for a while now.

As we move forward with the plan for [Notebook v7](https://github.com/jupyter/notebook/issues/6266), we should consider updating these templates accordingly, since we'll also be using the notebook repo to develop Notebook v7 (RetroLab) and track issues.

The new issue templates should make it clear to the users there is a new stream of work happening in the repo for Notebook v7. And Notebook v6 tracked in the `6.x` branch.

cc @Zsailer @tonyfast @afshin since this was discussed at some of the weekly meetings: https://github.com/jupyter/notebook-team-compass/issues/5

**Comment by Zsailer** [comment]
Just updated the `notebook` repo to allow opening an issue.

**Comment by jtpio** [comment]
> This is even worse now because there is literally no way from the "choose" page to open a new issue.

Wasn't it on purpose, so we get the issue templates setup first to not confuse folks with the v6 to v7 transition?

**Comment by jtpio** [comment]
Pinging other regular attendees of the Notebook meeting for help with this, thanks!

@jweill-aws @fpliger @kevingoldsmith @echarles

**Comment by echarles** [comment]
Current state is the following. Linking to jupyterlab could be changed now that main branch target v7. This will for sure evolve based on yesterday discussion (nbclassic..) 

```
Is this a common issue? See our Docs.
Before posting an issue here, make sure your issue hasn't already been addressed here.

Do you need support or a question answered? See Jupyter Discourse.
If you have a question or you're having issues installing Jupyter Notebook, try posting on Discourse. There are lots of friendly Joyvans there to help!

Do you have a feature request? See JupyterLab.
Jupyter Notebook is in a maintenance-only phase. We won't likely accept new features; instead, we recommend you check out JupyterLab for new features and support.
```

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6939, thanks @RRosio!
