### ISSUE TITLE
Move issues from the RetroLab repo to the Notebook repo

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook-team-compass#9]
Opening the issue here to discuss the strategy we would like to follow to move the issues from https://github.com/jupyterlab/retrolab to https://github.com/jupyter/notebook, now that the `main` branch is targeting Notebook v7.

At the Jupyter triage meeting today @krassowski suggested we could temporarily move the retrolab repo to the `jupyter` organization on GitHub for maybe 30 minutes. Since the two repos would be under the same org we could use the "Tranfer Issue" feature from the GitHub UI directly.

When issues have been moved, we move the retrolab repo back to the `jupyterlab` organization.

This would avoid having lots of issues open by Meeseeks, and we keep the original authors.

What do you think?

**Comment by damianavila** [comment]
+1 on the simplest approach and what you describe (temporary migration) seems totally reasonable to me if we can avoid the non-useful noise.

**Comment by jtpio** [comment]
Starting the transfer now.

Will move the repo back to the `jupyterlab` organization once finished.

**Comment by jtpio** [comment]
Closing as all the relevant issues have now been transferred and added to the 7.0 milestone: https://github.com/jupyter/notebook/milestone/45

The RetroLab repo has been transferred back to the `jupyterlab` organization: https://github.com/jupyterlab/retrolab
